// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikvcbfflveizztkipdop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdmNiZmZsdmVpenp0a2lwZG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzE0NTMsImV4cCI6MjA3MjY0NzQ1M30.Cg-W-gLdftiH0Oz-vib8LN-X6dcHUVVKfbq9xORcb0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});